/**
 * Central branding configuration.
 *
 * Agencies buying the source code can rebrand the entire product by editing
 * this single file — no need to hunt through dozens of components.
 */
export const brand = {
  name: "AI Traffic Analyzer",
  shortName: "Traffic AI",
  tagline: "Self-hosted AI traffic intelligence",
  description:
    "Convert traffic video into structured vehicle data, directional flow, zone analytics and professional reports.",
  // Logo path under /public
  logo: "/brand/logo.svg",
  logoMark: "/brand/mark.svg",
  // Primary accent color — deep amber (road-sign ochre)
  primaryColor: "#b45309",
  supportEmail: "support@example.com",
  supportUrl: "https://example.com/support",
  docsUrl: "https://example.com/docs",
  reportFooter: "Generated by AI Traffic Analyzer — self-hosted traffic intelligence.",
  // When true, the footer shows a discreet "Powered by" credit.
  showPoweredBy: false,
} as const;

export type Brand = typeof brand;
