"use client";

import { useEffect } from "react";
import { useNav } from "../nav-context";
import { useFetch } from "../use-fetch";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Play, FolderKanban, ArrowRight, Sparkles, Settings2 } from "lucide-react";

interface ProjectList {
  projects: { id: string; name: string; description: string | null; _count: { videos: number; analyses: number } }[];
}
interface AnalysisList {
  analyses: { id: string; project: { id: string; name: string }; status: string; video: { filename: string; duration: number } }[];
}

export function DemoView() {
  const { openAnalysis, navigate } = useNav();
  const { data: projects, loading } = useFetch<ProjectList>("/api/projects");
  const { data: analyses } = useFetch<AnalysisList>("/api/analysis");

  const demoProject = projects?.projects.find((p) => p.name.includes("Downtown"));
  const demoAnalysis = analyses?.analyses.find((a) => a.project.name.includes("Downtown") && a.status === "COMPLETED");

  useEffect(() => {
    // Auto-open the demo analysis on first load if present
    if (demoAnalysis) {
      // intentionally do not auto-redirect; show a landing card
    }
  }, [demoAnalysis]);

  if (loading) return <Skeleton className="h-[400px] rounded-xl" />;

  return (
    <div className="mx-auto max-w-4xl space-y-6">
      <Card className="overflow-hidden">
        <div className="bg-gradient-to-br from-primary/15 via-primary/5 to-transparent p-8">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-primary">
            <Sparkles className="h-3.5 w-3.5" /> Demo Mode
          </div>
          <h1 className="mt-2 text-2xl font-bold tracking-tight">Downtown Intersection Demo</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Explore a fully analyzed 4-way urban intersection with vehicles, tracks, zones, counting lines and events — all generated by the deterministic mock provider. No API key, no upload, no processing wait.
          </p>
        </div>
        <CardContent className="p-6">
          {demoAnalysis ? (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                <DemoStat label="Project" value="Downtown Intersection" />
                <DemoStat label="Duration" value="3:00" />
                <DemoStat label="Zones" value={`${demoProject?._count.analyses ?? 0 + 4}`} />
                <DemoStat label="Provider" value="mock" />
              </div>
              <div className="flex flex-wrap gap-2">
                <Button onClick={() => openAnalysis(demoAnalysis.id, demoAnalysis.project.id)} className="gap-2">
                  <Play className="h-4 w-4" /> Open Analysis Workspace
                </Button>
                <Button variant="outline" onClick={() => navigate("results", { analysisId: demoAnalysis.id, projectId: demoAnalysis.project.id })} className="gap-2">
                  View Results <ArrowRight className="h-4 w-4" />
                </Button>
                <Button variant="outline" onClick={() => navigate("reports", { analysisId: demoAnalysis.id, projectId: demoAnalysis.project.id })} className="gap-2">
                  Generate Report
                </Button>
                <Button variant="outline" onClick={() => navigate("zones", { projectId: demoAnalysis.project.id })} className="gap-2">
                  Edit Zones
                </Button>
                <Button variant="outline" onClick={() => navigate("lines", { projectId: demoAnalysis.project.id })} className="gap-2">
                  Edit Lines
                </Button>
              </div>
            </div>
          ) : (
            <div className="space-y-3">
              <p className="text-sm text-muted-foreground">The demo project is loading. If it doesn't appear, the seed may not have run.</p>
              <Button variant="outline" onClick={() => navigate("projects")} className="gap-2">
                <FolderKanban className="h-4 w-4" /> Browse Projects
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <Card>
          <CardContent className="p-5">
            <Settings2 className="h-6 w-6 text-primary" />
            <h3 className="mt-2 font-semibold">Connect a real AI provider</h3>
            <p className="mt-1 text-xs text-muted-foreground">Switch from the mock provider to a real vision API or local inference server when you're ready to analyze your own footage.</p>
            <Button size="sm" variant="outline" className="mt-3" onClick={() => navigate("settings")}>Configure Provider</Button>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-5">
            <FolderKanban className="h-6 w-6 text-primary" />
            <h3 className="mt-2 font-semibold">Create your own project</h3>
            <p className="mt-1 text-xs text-muted-foreground">Set up zones, counting lines and rules for your own traffic study, then upload video and run analysis.</p>
            <Button size="sm" variant="outline" className="mt-3" onClick={() => navigate("projects")}>New Project</Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function DemoStat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border bg-card p-3">
      <div className="truncate text-base font-bold tabular-nums">{value}</div>
      <div className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</div>
    </div>
  );
}
